### ISSUE TITLE
Not working with ImpressPages 4.9.0

### ISSUE THREAD

**Issue by carlos22** [impresspages-plugins/SitemapXml#3]
Error:
<br />
<b>Fatal error</b>:  Call to a member function getUrlPath() on null in <b>/var/www/htdocs/web/Ip/Functions.php</b> on line <b>595</b><br />

I'm not really sure why this happens. Used latest master from this repo.

**Comment by maskas** [comment]
Works for me on 4.9.0. But the error suggests me, that you may have something wrong with your languages. If you open Admin -> Languages, do you have the first language "visible"?

**Comment by carlos22** [comment]
Hmm ok. The language is visible - it is only one language and all are visible. Is there any way to track the error down? The debug options in config.php are on.

**Comment by maskas** [comment]
Sure it is. You can use PHP debugger :) but I guess you haven't used one before. In that case you can open /var/www/htdocs/web/Ip/Functions.php and do some 

echo 'step1'
...
echo 'step1'
...
var_dump($language)

It looks like $language is null on line 595. In theory it isn't possible. So you have to track it down how it happens.

**Comment by carlos22** [comment]
Readded english as language - now it is working. The ipHomeUrl function was called with "en" - but I deleted the "en" entry using the admin. Thanks for your help.
